[package]
name = "pctlweb"
version = "0.1.0"
authors = ["Daniel Danner <daniel@danner.de>"]
edition = "2018"

[dependencies]
rocket = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
phf = { version = "0.11.1", features = ["macros"] }
base64 = "0.13.1"
